import { generateTheme, themeToCss } from '../src/lib/theme/generate';

const seedArg = process.argv[2];
const seed = seedArg ?? '#4F6CFF';

if (!seed.match(/^#[0-9a-fA-F]{6}$/)) {
  console.error(`Invalid hex color: "${seed}". Expected format: #RRGGBB`);
  process.exit(1);
}

const theme = generateTheme(seed);
const css = themeToCss(theme);

console.log(`/* Generated by scripts/generate-theme.ts — seed: ${seed} */`);
console.log(css);
